// -- all routes consts
const String introSliderScreenRoute = 'introslider_screen';
const String homepageScreenRoute = 'homepage_screen';
const String loginScreenRoute = 'login_screen';
const String signUpScreenRoute = 'signup_screen';
const String forgotPasswordScreenRoute = 'forgot_password_screen';
const String userProfileScreenRoute = 'user_profile_screen';
const String completedTestsRoute = 'completed_tests_screen';
const String testViewScreenRoute = 'test_view_screen';